# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "FlySearch: Exploring how vision-language models explore"
site_description: "A benchmark for evaluating vision-language models in simulated 3D, outdoor, photorealistic environments."
site_url: https://flysearch.pardyl.com
copyright: Copyright &copy; 2025 FlySearch authors
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
  icon:
    logo: material/quadcopter
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
plugins:
  - search
  - social
  - macros:
      module_name: docs/main
  - table-reader:
      data_path: "docs/data"
repo_url: https://github.com/gmum/FlySearch
repo_name: gmum/FlySearch
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gmum/FlySearch

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

nav:
  - The benchmark: index.md
  - Getting started:
      - Setup: getting-started/10-setup.md
      - Running the benchmark: getting-started/20-running.md
  - User guide:
      - FlySearch.py: user-guide/00-script.md
      - Conversation: user-guide/10-conversation.md
      - Result analysis: user-guide/20-result-analysis.md
      - Adding new models: user-guide/30-custom-agents.md
  - Internals:
      - Environment: internals/10-environment.md
      - Custom environments: internals/30-custom-environments.md
      - Custom assets: internals/40-custom-assets.md
      - Building Unreal: internals/50-building-unreal.md
  - Examples: logs/ # Separate webapp, not handled by mkdocs
